### ISSUE TITLE
[Feature Request]: TokenGroup optional onDismiss

### ISSUE THREAD

**Issue by kamaz** [cloudscape-design/components#1011]
### Description

We use TokenGroup to allow users to add emails and manage them during onboarding. As part of the process, we would like to use the component as part of "Review" where we don't expect users to update values but we want to keep the same visual effect as they had when adding. 

It would be great if when `onDismiss` is not being passed to `TokenGroup` that would skip creating a wrapper in [`TokenGroup`](https://github.com/cloudscape-design/components/blob/main/src/token-group/internal.tsx#L49) and hide the `X` button.

Happy to contribute to making the change if you are happy with the above.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by fr0stf0x** [comment]
This is a workaround im using

you can add a class to `TokenGroup` say "readonly-token-group"

and style for it

```css
.readonly-token-group {
  [class*="awsui_dismiss-button"] {
    display: none !important;
  }

  [class*="awsui_option"] {
    padding-right: 8px !important;
  }

  &.no-label {
    padding-top: 0 !important;
  }
}
```
