### ISSUE TITLE
[Feature Request]: `white-space` style will be override for items under `ButtonDropdown`

### ISSUE THREAD

**Issue by franky920920** [cloudscape-design/components#1960]
### Description

The `ButtonDropdown` component's item will ~~not~~ wrap text if you have a `white-space` property set and rides on it. 

For me, its because I have 
```css
* {
  white-space: break-spaces;
}
```
set globally. (for line break `\n` in i18n strings)

---
My workaround: add custom className, for example `buttonDropdownFix` (I know this is discouraged but like I said, its a workaround), and have css like
```css
.buttonDropdownFix ul > li > span {
    white-space: nowrap;
}
```

Please let me know if any questions. Thanks! 

_All opinions are my own._

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests
